# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7efb311d6611099072b9c24632af3366f2073dae482804e3513266b83d7faac689f59e2e003f46b2b5196974db34320cabcb2df3a94d4beb068ba9a9b2dfe8

test:
  secret_key_base: e1a585a0e8485cdf3b6a6cf36c87398929c3a092f360a1ae28fa97c35a4219f9b6232ff73c200c7de904b5dafd83eb9ed51fef4a60c331620ef1ee102eec702f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
